#!/bin/bash

cd src

echo -e "\e[1m\e[37mGenerating grammer2.5.inc\e[0m"
python jt.py jmptable.z80 grammer2.5.inc
cp grammer2.5.inc ../docs/grammer2.5.inc

echo -e "\e[1m\e[37mAssembling App\e[0m"
spasm grammer.z80 ../bin/remmag.8xk
